import enum

class MethodList(enum.Enum):
    drawResult = "Draw result"
    originalReference = "Original reference"
    colorDetect = "Color detect"
    matchingTemplate = "Matching template"
    gaussianBlur = "Gaussian Blur"
    medianBlur = "Median blur"
    blur = "Blur"
    cvtColor = "Convert Color"
    findContour = "Find contour"
    fillContour = "Fill contour"
    countContour = "Count contour"
    focusChecking = "Focus checking"
    getImageInsideContour = "Image inside contour"
    countNonzero = "Count Nonzero"
    bitwiseAnd = "Bitwise and"
    bitwiseOr = "Bitwise Or"
    bitwiseNot = "Bitwise Not"
    bitwiseXor = "Bitwise Xor"
    threshold ="Threshold"
    threshold_average = "Threshold average"
    adaptiveThreshold = "Adaptive threshold"
    black2White = "Black to white"
    white2Black = "White to black"
    dilate = "Dilate"
    erode = "Erode"
    subtractionMog2 = "Subtraction MOG2"
    subtractionKNN = "Subtraction KNN"
    houghCircle = "Find circle"
    houghLines = "Find lines"
    houghLinesP = "Find lines P"
    averageHoughCircle = "Find average circle"
    inRange = "In range"
    hlsInRange = "HLS range"
    hsvInRange = "HSV range"
    bgrInRange = "BGR range"
    bgr_hsvRange = "BGR+HSV range"
    bgr_hlsRange = "BGR+HLS range"
    hsv_hlsRange = "HSV+HLS range"
    boltHeaderDetectionWithPytorchYolo4 = "Bolt header Torch-Yolo4"
    getSystemOffset = "Get System offset"
    canny = "Canny"
    rotate = "Rotate"
    flip = "Flip"
    translation = "Translation"
    referenceTranslation = "Reference translation"
    drawCircle = "Draw circle"
    getExtreme = "Get extreme"
    paint = "Paint"
    getMinAreaRect = "Get min area"
    barcodeReader = "Barcode reader"
    dataMatrixReader = "Data matrix reader"
    dataMatrixReaderWithArea= "Data matrix reader with min area"
    findChessBoardCorners = "Find chessboard corners"
    calibrationChessboard = "Calibration chessboard"
    resize = "Resize"
    minEnclosingCircle = "Min Enclosing Circle"
    fittingLine = "Fitting Line"
    fittingEllipse = "Fitting Ellipse"
    contourPerimeter = "Contour Perimeter"
    contourApproximation = "Contour Approximation"
    convexHull = "Convex Hull"
    connectionContour = "Connection Contours"
    splitChannel = "Split channel"
    ocr_tesseract = "OCR Tesseract"
    changeColor = "Change Color"
    ddk_scratch_dl = "DDK Scratch DL"
    distance_point_to_point = "Distance Point to Point"
    distance_point_to_line = "Distance Point to Line"
    angle_from_2_lines = "Angle From 2 Lines"
    ignore_areas = "Ignore Areas"
    rotate_with_angle = "Rotate With Angle"
    brightness_change = "Brightness Change"
    histogram_equalization = "Histogram Equalization"
    gama_correction = "Gama Correction"
    mesurand_conversion = "Measurand Conversion "
    reference_edge_corner = "Reference Edge Corner"
    floodFill = "Flood Fill"
    multi_select_area = "Multi Select Area"
    viet_ocr = "Viet OCR"
    contour_linear_regression = "Contour Linear Regression"
    segment_yolov8 = "Segment Yolov8"
    auto_multi_circle = "Multi Select Area 2 - circle"


class ValueMethodList(enum.Enum):
    colorDetect = "Color detect"
    matchingTemplate = "Matching template"
    countNonzero = "Count Nonzero"
    hlsInRange = "HLS range"
    hsvInRange = "HSV range"
    bgrInRange = "BGR range"
    bgr_hsvRange = "BGR+HSV range"
    bgr_hlsRange = "BGR+HLS range"
    hsv_hlsRange = "HSV+HLS range"

    @staticmethod
    def list():
        return list(map(lambda c: c.value, ValueMethodList))

class LocationMethodList(enum.Enum):
    matchingTemplate = "Matching template"
    findContour = "Find contour"
    fillContour = "Fill contour"
    getImageInsideContour = "Image inside contour"
    houghCircle = "Hough circle"
    houghLine = "Hough line"
    averageHoughCircle = "Average hough circle"

    @staticmethod
    def list():
        return list(map(lambda c: c.value, LocationMethodList))